# A Gentle Introduction to Numpy and Its Mega Alternative, PyTorch

This notebook borrows significant amount of code for the numpy part from Andrej Karpathy's [Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/).

## Numpy

[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python.

It provides a high-performance multidimensional array object, and tools for working with these arrays.

If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np
from time import time

In [2]:
a = np.array([1, 2, 3])
print('Array:', a)
print('Type:', type(a))
print('Shape:', a.shape)
a[0] = 5
a

Array: [1 2 3]
Type: <class 'numpy.ndarray'>
Shape: (3,)


array([5, 2, 3])

In [3]:
# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])
print('Shape:', b.shape)
b

Shape: (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b[0, 0], b[0, 1], b[1, 0]

(1, 2, 4)

In [5]:
a = np.zeros((2,2))
print('Shape:', a.shape)
a

Shape: (2, 2)


array([[0., 0.],
       [0., 0.]])

In [6]:
b = np.ones((1,2))
print('Shape:', b.shape)
b

Shape: (1, 2)


array([[1., 1.]])

In [7]:
c = np.full((2,2), 7)
print('Shape:', c.shape)
c

Shape: (2, 2)


array([[7, 7],
       [7, 7]])

In [8]:
d = np.eye(2)
print('Shape:', d.shape)
d

Shape: (2, 2)


array([[1., 0.],
       [0., 1.]])

In [9]:
e = np.random.random((2,2))  # Create an array filled with random values
print('Shape:', e.shape)
e

Shape: (2, 2)


array([[0.30130556, 0.93041278],
       [0.9873238 , 0.45118056]])

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Shape:', a.shape)
a

Shape: (3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [11]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [12]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print()
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)

[[5 6 7 8]] (1, 4)


In [13]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [14]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# An example of integer array indexing.
# The returned array will have shape (3,) and
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [16]:
# The above example of integer array indexing is equivalent to this:
np.array([a[0, 0], a[1, 1], a[2, 0]])

array([1, 4, 5])

In [17]:
# When using integer array indexing, you can reuse the same
# element from the source array:
a[[0, 0], [1, 1]]

array([2, 2])

In [18]:
# Equivalent to the previous integer array indexing example
np.array([a[0, 1], a[0, 1]])

array([2, 2])

In [19]:
# Boolean mask
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [20]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
a[bool_idx]

array([3, 4, 5, 6])

In [21]:
# We can do all of the above in a single concise statement:
a[a > 2]

array([3, 4, 5, 6])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [23]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [24]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [25]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [26]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [28]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [29]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## PyTorch

Numpy is such a wonderful framework to do computing right?

Numpy is a great framework, but it cannot utilize GPUs to accelerate its numerical computations. 

For modern deep neural networks, GPUs often provide speedups of **50x** or greater, so unfortunately numpy won’t be enough for modern deep learning.

Here we introduce the most fundamental PyTorch concept: the Tensor. A PyTorch Tensor is conceptually identical to a numpy array: a Tensor is an n-dimensional array, and PyTorch provides many functions for operating on these Tensors. Like numpy arrays, PyTorch Tensors do not know anything about deep learning or computational graphs or gradients; they are a generic tool for scientific computing.

Before we start, **let's see the difference!**

In [30]:
# Suppose we need to do 25000000 times multiplication

# We fisrt use numpy to do the computation.
a = np.random.random((5000, 5000))
b = np.random.random((5000, 5000))
start = time()
for i in range(50):
    c = a * b
print('Time used ->', time() - start)

Time used -> 4.455638408660889


In [31]:
import torch as T

In [32]:
# Now we use PyTorch
a = T.randn((5000, 5000))
b = T.randn((5000, 5000))
start = time()
for i in range(50):
    c = a * b
cpu_time = time() - start
print('Time used ->', cpu_time)

Time used -> 1.5368340015411377


In [33]:
# Now we use PyTorch with GPU
if T.cuda.is_available():
    device = T.device('cuda')
    a = T.randn((5000, 5000), device=device)
    b = T.randn((5000, 5000), device=device)
    start = time()
    for i in range(50):
        c = a * b
    gpu_time = time() - start
    print('Time used ->', gpu_time)

Time used -> 0.0058171749114990234


In [34]:
cpu_time / gpu_time

264.1890651256199